"""create tables

Revision ID: 9fa809be18ff
Revises: 
Create Date: 2025-09-03 23:54:18.177946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa809be18ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('airline', sa.VARCHAR(length=100), nullable=False),
    sa.Column('departure_airport', sa.VARCHAR(length=50), nullable=False),
    sa.Column('arrival_airport', sa.VARCHAR(length=50), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('arrival_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_index(op.f('ix_flights_flight_id'), 'flights', ['flight_id'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_class', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ticket_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('delay_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_bookings_booking_id'), 'bookings', ['booking_id'], unique=False)
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
