"""final_db_schema_updated

Revision ID: c0cfc4c1df8a
Revises: c204f6cc56a3
Create Date: 2025-09-07 17:05:33.497531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0cfc4c1df8a'
down_revision: Union[str, Sequence[str], None] = 'c204f6cc56a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('final_db_schema', 'ARRIVAL_DELAY_PREDICTED',
               existing_type=sa.NUMERIC(precision=5, scale=15),
               type_=sa.DECIMAL(precision=20, scale=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('final_db_schema', 'ARRIVAL_DELAY_PREDICTED',
               existing_type=sa.DECIMAL(precision=20, scale=15),
               type_=sa.NUMERIC(precision=5, scale=15),
               existing_nullable=False)
    # ### end Alembic commands ###
