"""create final_db_schema

Revision ID: c204f6cc56a3
Revises: ed4652075b0a
Create Date: 2025-09-07 17:00:35.585166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c204f6cc56a3'
down_revision: Union[str, Sequence[str], None] = 'ed4652075b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_db_schema',
    sa.Column('FLIGHT_NUMBER', sa.Integer(), nullable=False),
    sa.Column('YEAR', sa.Integer(), nullable=False),
    sa.Column('MONTH', sa.Integer(), nullable=False),
    sa.Column('DAY', sa.Integer(), nullable=False),
    sa.Column('DAY_OF_WEEK', sa.Integer(), nullable=False),
    sa.Column('AIRLINE', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ORIGIN_AIRPORT', sa.VARCHAR(length=20), nullable=False),
    sa.Column('DESTINATION_AIRPORT', sa.VARCHAR(length=20), nullable=False),
    sa.Column('SCHEDULED_DEPARTURE', sa.Integer(), nullable=False),
    sa.Column('DEPARTURE_TIME', sa.Integer(), nullable=False),
    sa.Column('DEPARTURE_DELAY', sa.Integer(), nullable=False),
    sa.Column('TAXI_OUT', sa.Integer(), nullable=True),
    sa.Column('SCHEDULED_TIME', sa.Integer(), nullable=True),
    sa.Column('DISTANCE', sa.Integer(), nullable=True),
    sa.Column('SCHEDULED_ARRIVAL', sa.Integer(), nullable=False),
    sa.Column('ARRIVAL_DELAY_PREDICTED', sa.DECIMAL(precision=5, scale=15), nullable=False),
    sa.PrimaryKeyConstraint('FLIGHT_NUMBER')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('final_db_schema')
    # ### end Alembic commands ###
