FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
ENV VITE_BACKEND_URL=http://127.0.0.1:8000

COPY . .

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
