services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ✅ Frontend served via Nginx
  frontend:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: frontend_container
    ports:
      - "80:80"
    env_file: ./.env               
    depends_on:
      - node-backend
    restart: unless-stopped

  node-backend:
    container_name: node_backend
    build:
      context: ./backend_dev
      dockerfile: Dockerfile
    expose:
      - "3000"                  # Changed from 5001 to 3000
    env_file:
      - ./.env
    depends_on:
      - ml-service
      - db
    restart: unless-stopped

  ml-service:
    container_name: ml_service
    build:
      context: ./backend_dev/ml_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: