services:

  db:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: madhurima
      POSTGRES_DB: flightdb
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    depends_on:
      - db
  node-backend:
    container_name: node_backend
    build:
      context: ./backend_dev
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    depends_on:
      - ml-service
      - frontend

  ml-service:
    container_name: ml_service
    build:
      context: ./backend_dev/ml_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: