"""create flights table

Revision ID: 0521e3a05c38
Revises: 9fa809be18ff
Create Date: 2025-09-06 21:19:51.981241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0521e3a05c38'
down_revision: Union[str, Sequence[str], None] = '9fa809be18ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'delay_status')
    op.drop_column('bookings', 'delay_minutes')
    op.add_column('flights', sa.Column('delay_minutes', sa.Integer(), nullable=True))
    op.add_column('flights', sa.Column('delay_status', sa.VARCHAR(length=50), nullable=True))
    op.alter_column('flights', 'departure_airport',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('flights', 'arrival_airport',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('flights', 'departure_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('flights', 'arrival_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flights', 'arrival_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('flights', 'departure_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('flights', 'arrival_airport',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('flights', 'departure_airport',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('flights', 'delay_status')
    op.drop_column('flights', 'delay_minutes')
    op.add_column('bookings', sa.Column('delay_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('delay_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
